CREATE DATABASE IF NOT EXISTS guess_songs_king;
USE guess_songs_king;

CREATE TABLE IF NOT EXISTS host (
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nickname VARCHAR(128) NOT NULL,
  email VARCHAR(128) NOT NULL,
  password VARCHAR(512) NOT NULL,
  
  UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS party (
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  host_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  questions VARCHAR(128) NOT NULL,

  FOREIGN KEY(host_id) REFERENCES host(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS track (
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  party_id BIGINT UNSIGNED NOT NULL,
  artist VARCHAR(128) NOT NULL,
  name VARCHAR(128) NOT NULL,
  q_type BIGINT UNSIGNED NOT NULL,

  FOREIGN KEY(party_id) REFERENCES party(id) ON DELETE CASCADE ON UPDATE CASCADE
);